inputs:
  port:
    description: 'Port for node application to run'
    default: 7001
  environment: 
    description: 'Environment for node application'
    default: 'dev'

runs:   
  using: "composite"
  steps:
    - name: Print output
      run: echo Deployment to ${{ inputs.environment }} has started ..
      shell: cmd

    - name: Install dependencies
      working-directory: course-js-api-framework-file
      run: npm install
      shell: cmd

    - name: Install pm2
      working-directory: course-js-api-framework-file
      run: npm install -g pm2
      shell: cmd

    - name: Delete process
      working-directory: python-greetings-file
      run: pm2 delete greetings-app-${{ inputs.environment }} & set "errorlevel=0"
      shell: cmd

    - name: Start process
      working-directory: python-greetings-file
      run: pm2 start app.py --name greetings-app-${{ inputs.environment }} -- --port ${{ inputs.port }}
      shell: cmd
