name: CI_workflow

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  install-pip-deps:
    name: Install pip deps
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'zer0ant/python-greetings'
          path: 'python-greetings-file'
      - uses: ./.github/actions/install


  deploy-to-dev:
    name: Deploy to DEV
    runs-on: self-hosted
    needs: [install-pip-deps]

    steps:
      - name: Deploy to DEV success
        run: echo Deployment to DEV has started ..
      - uses: actions/checkout@v3.5.2
      - uses: actions/checkout@v3.5.2
        with:
          repository: 'zer0ant/course-js-api-framework'
          path: 'course-js-api-framework-file'
      - uses: ./.github/actions/deploy
        with: 
          port: 7001
          environment: 'dev'

  test-on-dev:
    name: Test on DEV
    runs-on: self-hosted
    needs: [deploy-to-dev]

    steps:
      - name: Test success
        run: echo Testing on DEV has started ..
    #  - uses: actions/checkout@v4
    #  - uses: actions/checkout@v4
    #    with:
    #      repository: 'zer0ant/api-automation'
    #      path: 'api-tests'
    #  - uses: ./.github/actions/test
    #    with: 
    #      environment: 'DEV'


  deploy-to-staging:
    name: Deploy to staging
    runs-on: self-hosted
    needs: [test-on-dev]

    steps:
      - name: Deploy success
        run: echo Deployment to staging has started ..

  test-on-staging:
    name: Test on staging
    runs-on: self-hosted
    needs: [deploy-to-staging]

    steps:
      - name: Test success
        run: echo Testing on staging has started ..


  deploy-to-preprod:
    name: Deploy to preprod
    runs-on: ubuntu-latest
    needs: [test-on-staging]

    steps:
      - name: Deploy success
        run: echo Deployment to preprod has started ..

  test-on-preprod:
    name: Test on preprod
    runs-on: self-hosted
    needs: [deploy-to-preprod]

    steps:
      - name: Test success
        run: echo Testing on preprod has started ..


  deploy-to-prod:
    name: Deploy to prod
    runs-on: self-hosted
    needs: [test-on-preprod]

    steps:
      - name: Deploy success
        run: echo Deployment to prod has started ..

  test-on-prod:
    name: Test on prod
    runs-on: self-hosted
    needs: [deploy-to-prod]

    steps:
      - name: Test success
        run: echo Testing on prod has started ..
